import { DaVinciMarker, DaVinciEditReport, VideoMetadata, PlatformId } from '../types';

/**
 * Generates DaVinci Resolve compatible Marker CSV.
 * Supported in DaVinci Resolve:
 * Right-click Timeline in Media Pool -> Timelines -> Import -> Timeline Markers from CSV
 * Columns: "Record In", "Record Out", "Duration", "Marker Name", "Description", "Color"
 */
export function generateDaVinciMarkerCSV(markers: DaVinciMarker[]): string {
  const headers = ['Record In', 'Record Out', 'Duration', 'Marker Name', 'Description', 'Color'];
  
  const escapeCsv = (str: string) => `"${(str || '').replace(/"/g, '""')}"`;

  const rows = markers.map((m) => [
    escapeCsv(m.timecodeIn),
    escapeCsv(m.timecodeOut),
    escapeCsv(String(m.durationFrames || 1)),
    escapeCsv(m.name),
    escapeCsv(m.comment),
    escapeCsv(m.color),
  ]);

  return [headers.join(','), ...rows.map((r) => r.join(','))].join('\r\n');
}

/**
 * Generates CMX 3600 EDL with DaVinci Resolve Marker annotations.
 * This is an industry standard EDL that DaVinci Resolve can import directly as timeline markers.
 */
export function generateDaVinciEDL(
  markers: DaVinciMarker[],
  video: VideoMetadata,
  fps: number = 30
): string {
  const title = (video.fileName || 'EXPORT_TIMELINE')
    .replace(/[^a-zA-Z0-9_]/g, '_')
    .slice(0, 32);

  const lines = [
    `TITLE: ${title}`,
    `FCM: NON-DROP FRAME`,
    ``,
  ];

  markers.forEach((m, idx) => {
    const eventNum = String(idx + 1).padStart(3, '0');
    // Standard edit line: EventNum Reel Track EditType SourceIn SourceOut RecordIn RecordOut
    lines.push(
      `${eventNum}  AX       V     C        ${m.timecodeIn} ${m.timecodeOut} ${m.timecodeIn} ${m.timecodeOut}`
    );
    lines.push(`* FROM CLIP NAME: ${video.fileName || 'source_clip.mp4'}`);
    lines.push(`* MARKER: ${m.timecodeIn} ${m.color} 1 ${m.name}`);
    lines.push(`* COMMENT: ${m.comment.replace(/\r?\n/g, ' ')}`);
    lines.push(``);
  });

  return lines.join('\r\n');
}

/**
 * Generates a comprehensive, human-readable DaVinci Resolve Action Plan Report in Markdown.
 */
export function generateDetailedMarkdownReport(
  report: DaVinciEditReport,
  video: VideoMetadata,
  selectedPlatform: PlatformId
): string {
  const targetScore = report.platformScores[selectedPlatform];

  return `# DaVinci Resolve Master Edit Plan & Platform Audit
**Generated by Video Quality & Platform Auditor**
**Date:** ${new Date().toLocaleString()}
**Target Platform:** ${selectedPlatform.toUpperCase()}
**Platform Suitability Score:** ${targetScore?.score || 0}/100 (${(targetScore?.status || 'review').toUpperCase()})

---

## 1. Source Footage Technical Profile
- **File Name:** ${video.fileName}
- **File Size:** ${video.fileSizeFormatted} (${(video.fileSizeBytes / (1024 * 1024)).toFixed(1)} MB)
- **Duration:** ${video.durationFormatted} (${video.durationSeconds.toFixed(2)}s)
- **Native Resolution:** ${video.width} x ${video.height}
- **Aspect Ratio:** ${video.aspectRatio}
- **Timeline Frame Rate:** ${video.fps} fps
- **Estimated Bitrate:** ${video.estimatedBitrateMbps}

---

## 2. Platform Compliance Scorecards
| Platform | Score | Status | Primary Guideline |
| :--- | :--- | :--- | :--- |
| **TikTok** | ${report.platformScores.tiktok.score}% | ${report.platformScores.tiktok.status.toUpperCase()} | 9:16 Portrait, Safe Zones, 2.5s Hook |
| **YouTube** | ${report.platformScores.youtube.score}% | ${report.platformScores.youtube.status.toUpperCase()} | 16:9 Long-form or 9:16 Shorts, -14 LUFS |
| **Facebook** | ${report.platformScores.facebook.score}% | ${report.platformScores.facebook.status.toUpperCase()} | Subtitles mandatory (85% silent autoplay) |
| **Rumble** | ${report.platformScores.rumble.score}% | ${report.platformScores.rumble.status.toUpperCase()} | High bitrate landscape, podcast/commentary pacing |

### Executive Summary:
${report.overallSummary}

### First 3-Seconds Hook Analysis:
- **Hook Rating:** ${report.hookEvaluation.score}/100
- **Assessment:** ${report.hookEvaluation.firstThreeSecondsVerdict}
- **Action Plan:** ${report.hookEvaluation.recommendation}

---

## 3. DaVinci Resolve Timeline Markers
Import into DaVinci Resolve using:
\`Media Pool > Right Click Timeline > Timelines > Import > Timeline Markers from CSV/EDL\`

| Timecode In | Timecode Out | Color | Marker Name | DaVinci Page / Action |
| :--- | :--- | :--- | :--- | :--- |
${report.davinciMarkers
  .map(
    (m) =>
      `| \`${m.timecodeIn}\` | \`${m.timecodeOut}\` | **${m.color}** | ${m.name} | ${m.comment} |`
  )
  .join('\n')}

---

## 4. DaVinci Edit Page Instructions (Trims, Zooms & Cuts)
${report.editPageAdvice
  .map(
    (e, i) => `### Cut/Adjustment ${i + 1} at \`${e.timecode}\`
- **Recommended Action:** ${e.action}
- **Editor Rationale:** ${e.reason}
`
  )
  .join('\n')}

---

## 5. DaVinci Color Page Grading Guide
${report.colorPageAdvice
  .map(
    (c, i) => `### Color Node ${i + 1}: ${c.nodeType} (\`${c.timecode}\`)
- **Suggested Adjustment:** ${c.suggestion}
- **DaVinci Palette/Tool:** \`${c.davinciTool}\`
`
  )
  .join('\n')}

---

## 6. DaVinci Fairlight Audio Mastering
${report.fairlightAudioAdvice
  .map(
    (a, i) => `### Audio Track Process ${i + 1}
- **Target Integrated Loudness:** \`${a.targetLufs} LUFS\`
- **Detected Phenomenon:** ${a.issue}
- **Fairlight Fix:** ${a.solution}
- **Recommended Fairlight VST/Processor:** \`${a.davinciProcessor}\`
`
  )
  .join('\n')}

---

## 7. Fusion & Safe Zone Guidelines (${selectedPlatform.toUpperCase()})
${report.fusionSafeZoneAdvice
  .map(
    (f) => `### ${f.platform}
- **Safe Zone Status:** ${f.safeZoneStatus}
- **Action Required:** ${f.action}
`
  )
  .join('\n')}

---
*Report formatted for Blackmagic Design DaVinci Resolve 18 & 19.*
`;
}

/**
 * Triggers a browser file download for a string blob.
 */
export function downloadFile(content: string, filename: string, mimeType: string) {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  setTimeout(() => URL.revokeObjectURL(url), 1000);
}
